### ISSUE TITLE
无法点击

### ISSUE THREAD

**Issue by blooming2017** [iHTCboy/CampusOfGLUT#1]
工程运行起来，都是灰色的，无法点击，无法创建新工程

**Comment by iHTCboy** [comment]
@blooming2017 请问你说的是具体是怎么样，能不能截图看看啊。最近比较忙，下月有空在更新适配一下iPhoneX 和 Xcode10啊。

**Comment by iHTCboy** [comment]
现在已经提交v5.0.0  适配iPhoneX的版本，有问题可以在联系我啊。
